#' @title LLM Export Layer
#' @description Serialize the App Brain to JSON or Markdown for consumption
#'   by LLMs and agents.
#' @name brain_export
NULL

# ---- JSON export ------------------------------------------------------------

#' Export App Brain to JSON
#'
#' Produces a structured JSON string suitable for pasting into an LLM context
#' or saving as a file for agent consumption.
#'
#' @param brain App Brain from build_brain()
#' @param file Optional file path to write JSON. NULL returns the string.
#' @param pretty Logical. Pretty-print the JSON (default TRUE).
#' @return Invisibly returns the JSON string.
#' @export
export_brain_json <- function(brain, file = NULL, pretty = TRUE) {
  if (!requireNamespace("jsonlite", quietly = TRUE)) {
    rlang::abort(paste0(
      "export_brain_json() requires the 'jsonlite' package, which is not installed. ",
      "Install it with: install.packages(\"jsonlite\"). ",
      "Alternatively, use export_brain_markdown() which has no extra dependencies."
    ))
  }

  payload <- .brain_to_list(brain)
  json    <- jsonlite::toJSON(payload, pretty = pretty, auto_unbox = TRUE,
                               na = "null", null = "null")

  if (!is.null(file)) {
    writeLines(json, file)
    message("Brain JSON written to: ", file)
  }

  invisible(json)
}

# ---- Markdown export --------------------------------------------------------

#' Export App Brain to Markdown
#'
#' Produces a human- and LLM-readable Markdown document summarising the app
#' structure, reactive graph, and insights.
#'
#' @param brain App Brain from build_brain()
#' @param file Optional file path to write Markdown. NULL returns the string.
#' @return Invisibly returns the Markdown string.
#' @importFrom utils head
#' @export
export_brain_markdown <- function(brain, file = NULL) {
  s       <- brain$summary
  proj    <- brain$project
  nodes   <- brain$nodes
  edges   <- brain$edges
  ins     <- brain$insights
  issues  <- brain$issues
  files   <- brain$files

  app_name <- if (!is.null(proj$root_path))
    basename(proj$root_path) else "Shiny App"

  lines <- character()
  emit  <- function(...) lines <<- c(lines, paste0(...))

  emit("# App Brain: ", app_name)
  emit("")
  emit("> Generated by shinybrain ", .brain_version(brain),
       " on ", format(Sys.time(), "%Y-%m-%d %H:%M UTC", tz = "UTC"))
  emit("")

  # --- Summary
  emit("## Summary")
  emit("")
  emit("| Metric | Value |")
  emit("|--------|-------|")
  emit("| Files | ", s$n_files, " |")
  emit("| Reactive contexts | ", s$n_contexts, " |")
  emit("| Graph nodes | ", s$n_nodes, " |")
  emit("| Graph edges | ", s$n_edges, " |")
  emit("| Unresolved references | ", s$n_unresolved, " |")
  emit("| Max dependency chain | ", s$max_chain_depth, " hops |")
  emit("| Complexity | ", s$complexity$label,
       " (", s$complexity$score, "/100) |")
  emit("")

  # Node breakdown
  if (length(s$node_breakdown) > 0) {
    emit("**Node types:** ",
         paste(names(s$node_breakdown), "x", unlist(s$node_breakdown),
               collapse = " | "))
    emit("")
  }

  # --- Files
  if (nrow(files) > 0) {
    emit("## Files")
    emit("")
    for (i in seq_len(nrow(files))) {
      f <- files[i, ]
      emit("- **", f$relative_path, "** (", f$role, ", ",
           f$line_count, " lines)")
    }
    emit("")
  }

  # --- Reactive graph
  emit("## Reactive Graph")
  emit("")
  emit("### Nodes")
  emit("")

  if (nrow(nodes) > 0) {
    for (i in seq_len(nrow(nodes))) {
      n <- nodes[i, ]
      loc <- if (!is.na(n$line_start)) paste0(" L", n$line_start) else ""
      src <- if (!is.na(n$file_id))   paste0(" (", n$file_id, loc, ")") else loc
      emit("- **", n$label, "** [`", n$node_type, "`]", src)
      if (!is.na(n$snippet) && nchar(n$snippet) > 0 &&
          isTRUE(brain$options$include_snippets)) {
        emit("")
        emit("  ```r")
        snippet_lines <- strsplit(n$snippet, "\n")[[1]]
        for (sl in head(snippet_lines, brain$options$snippet_max_lines)) {
          emit("  ", sl)
        }
        emit("  ```")
        emit("")
      }
    }
    emit("")
  } else {
    emit("_No nodes detected._")
    emit("")
  }

  emit("### Edges")
  emit("")
  if (nrow(edges) > 0) {
    # Build label lookup
    node_labels <- stats::setNames(nodes$label, nodes$node_id)
    for (i in seq_len(nrow(edges))) {
      e    <- edges[i, ]
      from <- node_labels[e$from_node_id] %||% e$from_node_id
      to   <- node_labels[e$to_node_id]   %||% e$to_node_id
      iso  <- if (isTRUE(e$is_isolated)) " _(isolated)_" else ""
      emit("- `", from, "` -> `", to, "` [", e$edge_type, "]", iso)
    }
    emit("")
  } else {
    emit("_No edges detected._")
    emit("")
  }

  # --- Insights
  emit("## Insights")
  emit("")
  if (nrow(ins) > 0) {
    sev_order <- c("error", "warning", "info")
    sev_icons <- c(error = "[ERROR]", warning = "[WARN]", info = "[INFO]")
    for (sev in sev_order) {
      rows <- ins[ins$severity == sev, ]
      if (nrow(rows) == 0) next
      for (i in seq_len(nrow(rows))) {
        icon <- sev_icons[sev]
        emit(icon, " **[", toupper(sev), "]** ", rows$message[i])
        emit("")
      }
    }
  } else {
    emit("_No insights generated; the app looks clean._")
    emit("")
  }

  # --- Issues (warnings/errors only)
  hard_issues <- issues[issues$severity %in% c("warning", "error"), ]
  if (nrow(hard_issues) > 0) {
    emit("## Issues")
    emit("")
    for (i in seq_len(nrow(hard_issues))) {
      iss <- hard_issues[i, ]
      emit("- **[", toupper(iss$severity), "]** ", iss$message)
    }
    emit("")
  }

  md <- paste(lines, collapse = "\n")

  if (!is.null(file)) {
    writeLines(md, file)
    message("Brain Markdown written to: ", file)
  }

  invisible(md)
}

# ---- Helpers ----------------------------------------------------------------

# Convert brain to a plain nested list (safe for jsonlite)
.brain_to_list <- function(brain) {
  nodes_list <- if (nrow(brain$nodes) > 0) {
    lapply(seq_len(nrow(brain$nodes)), function(i) {
      n <- brain$nodes[i, ]
      list(
        node_id        = n$node_id,
        node_type      = n$node_type,
        label          = n$label,
        qualified_name = n$qualified_name,
        file_id        = if (is.na(n$file_id)) NULL else n$file_id,
        line_start     = if (is.na(n$line_start)) NULL else n$line_start,
        usage_count    = n$usage_count,
        contains_isolate = n$contains_isolate,
        confidence     = n$confidence,
        snippet        = if (is.na(n$snippet)) NULL else n$snippet
      )
    })
  } else list()

  edges_list <- if (nrow(brain$edges) > 0) {
    # Build label lookup for readable from/to
    node_labels <- stats::setNames(brain$nodes$label, brain$nodes$node_id)
    lapply(seq_len(nrow(brain$edges)), function(i) {
      e <- brain$edges[i, ]
      list(
        from       = node_labels[e$from_node_id] %||% e$from_node_id,
        to         = node_labels[e$to_node_id]   %||% e$to_node_id,
        edge_type  = e$edge_type,
        is_isolated = e$is_isolated,
        confidence = e$confidence
      )
    })
  } else list()

  insights_list <- if (nrow(brain$insights) > 0) {
    lapply(seq_len(nrow(brain$insights)), function(i) {
      r <- brain$insights[i, ]
      list(category = r$category, severity = r$severity,
           label = r$label, message = r$message)
    })
  } else list()

  list(
    meta = list(
      app        = if (!is.null(brain$project$root_path))
                     basename(brain$project$root_path) else "unknown",
      generated  = format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC"),
      version    = .brain_version(brain)
    ),
    summary  = brain$summary,
    nodes    = nodes_list,
    edges    = edges_list,
    insights = insights_list
  )
}

.brain_version <- function(brain) {
  v <- tryCatch(brain$project$shinybrain_version[[1]], error = function(e) NULL)
  if (is.null(v) || length(v) == 0) "0.1.0" else v[1]
}

